# Generated by Django 3.2.6 on 2021-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(choices=[('supervisor', 'SuperVisor'), ('sales_agent', 'SalesAgent'), ('customer', 'Customer'), ('director', 'Director')], default='customer', max_length=100),
        ),
    ]
