# Generated by Django 3.2.6 on 2021-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_watchlist_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
